-- Ghost Secure demo schema for Vercel + Supabase (no custom backend).
-- Run this once in Supabase SQL Editor.

create table if not exists app_user (
  id text primary key,
  public_key text not null,
  created_at timestamptz not null default now()
);

create table if not exists conversation (
  id text primary key,
  created_at timestamptz not null default now()
);

create table if not exists conversation_member (
  id bigint generated by default as identity primary key,
  conversation_id text not null references conversation(id) on delete cascade,
  user_id text not null references app_user(id) on delete cascade,
  unique (conversation_id, user_id)
);

create index if not exists idx_cm_conversation on conversation_member(conversation_id);
create index if not exists idx_cm_user on conversation_member(user_id);

create table if not exists message (
  id text primary key,
  conversation_id text not null references conversation(id) on delete cascade,
  sender_id text not null references app_user(id) on delete cascade,
  ciphertext text not null,
  iv text not null,
  wrapped_keys jsonb not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz null
);

create index if not exists idx_msg_conv_created on message(conversation_id, created_at);
create index if not exists idx_msg_sender on message(sender_id);

create table if not exists friend_request (
  id text primary key,
  requester_id text not null references app_user(id) on delete cascade,
  target_user_id text not null references app_user(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists idx_fr_target_status on friend_request(target_user_id, status, created_at desc);
create index if not exists idx_fr_requester_status on friend_request(requester_id, status, created_at desc);
create unique index if not exists uniq_fr_pending_pair
  on friend_request(requester_id, target_user_id)
  where status = 'pending';

create table if not exists call_invite (
  id text primary key,
  call_id text not null unique,
  from_user_id text not null references app_user(id) on delete cascade,
  target_user_id text not null references app_user(id) on delete cascade,
  offer_sdp jsonb not null,
  answer_sdp jsonb null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'ended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_call_invite_target_status on call_invite(target_user_id, status, created_at desc);
create index if not exists idx_call_invite_from_status on call_invite(from_user_id, status, created_at desc);

alter table app_user disable row level security;
alter table conversation disable row level security;
alter table conversation_member disable row level security;
alter table message disable row level security;
alter table friend_request disable row level security;
alter table call_invite disable row level security;

alter publication supabase_realtime add table message;
alter publication supabase_realtime add table friend_request;
alter publication supabase_realtime add table call_invite;
