-- Ghost Secure demo schema for Vercel + Supabase (no custom backend).
-- Run this once in Supabase SQL Editor.

create table if not exists app_user (
  id text primary key,
  public_key text not null,
  created_at timestamptz not null default now()
);

create table if not exists conversation (
  id text primary key,
  created_at timestamptz not null default now()
);

create table if not exists conversation_member (
  id bigint generated by default as identity primary key,
  conversation_id text not null references conversation(id) on delete cascade,
  user_id text not null references app_user(id) on delete cascade,
  unique (conversation_id, user_id)
);

create index if not exists idx_cm_conversation on conversation_member(conversation_id);
create index if not exists idx_cm_user on conversation_member(user_id);

create table if not exists message (
  id text primary key,
  conversation_id text not null references conversation(id) on delete cascade,
  sender_id text not null references app_user(id) on delete cascade,
  ciphertext text not null,
  iv text not null,
  wrapped_keys jsonb not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz null
);

create index if not exists idx_msg_conv_created on message(conversation_id, created_at);
create index if not exists idx_msg_sender on message(sender_id);

alter table app_user disable row level security;
alter table conversation disable row level security;
alter table conversation_member disable row level security;
alter table message disable row level security;

alter publication supabase_realtime add table message;
