-- Ghost Secure full schema (Supabase + Symfony API/WS)
-- Safe to run on an empty database.
-- Also safe to re-run (idempotent as much as possible).

-- 1) Core users/conversations/messages
create table if not exists public.app_user (
  id varchar(36) primary key,
  public_key text not null,
  secret_hash varchar(255),
  created_at timestamp without time zone not null default now()
);

create table if not exists public.conversation (
  id varchar(36) primary key,
  created_at timestamp without time zone not null default now()
);

create table if not exists public.conversation_member (
  id bigint generated by default as identity primary key,
  conversation_id varchar(36) not null references public.conversation(id) on delete cascade,
  user_id varchar(36) not null references public.app_user(id) on delete cascade,
  unique (conversation_id, user_id)
);

create index if not exists idx_cm_conversation on public.conversation_member(conversation_id);
create index if not exists idx_cm_user on public.conversation_member(user_id);

create table if not exists public.message (
  id varchar(36) primary key,
  conversation_id varchar(36) not null references public.conversation(id) on delete cascade,
  sender_id varchar(36) not null references public.app_user(id) on delete cascade,
  ciphertext text not null,
  iv text not null,
  wrapped_keys jsonb not null,
  created_at timestamp without time zone not null default now(),
  expires_at timestamp without time zone null
);

create index if not exists idx_msg_conv_created on public.message(conversation_id, created_at);
create index if not exists idx_msg_sender on public.message(sender_id);

-- 2) Backend auth sessions (required by Symfony API + WS token validation)
create table if not exists public.user_session (
  id bigint generated by default as identity primary key,
  user_id varchar(36) not null references public.app_user(id) on delete cascade,
  token_hash varchar(128) not null,
  created_at timestamp without time zone not null default now(),
  expires_at timestamp without time zone not null
);

create unique index if not exists uniq_session_token on public.user_session(token_hash);
create index if not exists idx_session_user on public.user_session(user_id);

-- 3) Friend requests + call signaling
create table if not exists public.friend_request (
  id varchar(36) primary key,
  requester_id varchar(36) not null references public.app_user(id) on delete cascade,
  target_user_id varchar(36) not null references public.app_user(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamp without time zone not null default now()
);

create index if not exists idx_fr_target_status on public.friend_request(target_user_id, status, created_at desc);
create index if not exists idx_fr_requester_status on public.friend_request(requester_id, status, created_at desc);
create unique index if not exists uniq_fr_pending_pair
  on public.friend_request(requester_id, target_user_id)
  where status = 'pending';

create table if not exists public.call_invite (
  id varchar(36) primary key,
  call_id varchar(36) not null unique,
  from_user_id varchar(36) not null references public.app_user(id) on delete cascade,
  target_user_id varchar(36) not null references public.app_user(id) on delete cascade,
  offer_sdp jsonb not null,
  answer_sdp jsonb null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'ended')),
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now()
);

create index if not exists idx_call_invite_target_status
  on public.call_invite(target_user_id, status, created_at desc);
create index if not exists idx_call_invite_from_status
  on public.call_invite(from_user_id, status, created_at desc);

-- 4) Backward-compatible patch if app_user existed without secret_hash
alter table public.app_user add column if not exists secret_hash varchar(255);

-- 5) Realtime publication
do $$
begin
  alter publication supabase_realtime add table public.message;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.friend_request;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.call_invite;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

-- 6) RLS and grants for current app model
alter table public.app_user disable row level security;
alter table public.conversation disable row level security;
alter table public.conversation_member disable row level security;
alter table public.message disable row level security;
alter table public.user_session disable row level security;
alter table public.friend_request disable row level security;
alter table public.call_invite disable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter default privileges in schema public
grant select, insert, update, delete on tables to anon, authenticated;

alter default privileges in schema public
grant usage, select on sequences to anon, authenticated;

-- 7) Mark Doctrine migrations as already executed (for containers running migrate on boot)
create table if not exists public.doctrine_migration_versions (
  version varchar(191) primary key,
  executed_at timestamp without time zone default null,
  execution_time integer default null
);

insert into public.doctrine_migration_versions (version, executed_at, execution_time)
values
  ('DoctrineMigrations\\Version20260222000100', now(), 0),
  ('DoctrineMigrations\\Version20260224000100', now(), 0)
on conflict (version) do nothing;
